host requires protocol to be included
If the http or https protocol is not prefixed, the following error will be thrown:

```sh
ruby examples/example.rb
```

```
~/discourse_api/config.yml
~/discourse_api/lib/discourse_api/client.rb:193:in `check_subdirectory': undefined method `request_uri' for an instance of URI::Generic (NoMethodError)

      URI(host).request_uri != "/"
               ^^^^^^^^^^^^
        from ~/discourse_api/lib/discourse_api/client.rb:63:in `initialize'
        from examples/example.rb:7:in `new'
```